### ISSUE TITLE
EQ 条件中 json.Number 类型的数据会结果导致不匹配

### ISSUE THREAD

**Issue by childe** [childe/gohangout#101]
```
inputs:
    - Stdin:
        codec: json
filters:
    #- Convert:
        #fields:
            #a:
                #to: int
    - Drop:
        if:
            - 'EQ(a,1)'
    - Drop:
        if:
            - 'EQ($.b,"1")'
outputs:
    - Stdout:
        codec: json

```

运行结果:

```
% echo '{"a":1, "b":11}' | gohangout --config t.yml
{"@timestamp":"2020-09-22T20:47:53.27209+08:00","a":1,"b":11}
```

需要加上 Convert 才行, 因为 a 的值类型是 json.Number
