### ISSUE TITLE
生成null-null的索引，请教下会是哪里的问题

### ISSUE THREAD

**Issue by niuliwei1029** [childe/gohangout#116]
消费数据的时候，会生成包含null字符串的索引。从kibana看数据也没解析出来。kibana结果和配置如下：

```
inputs:
    - Kafka:
        topic:
            ops-iot-access: 1 
        codec: json 
        consumer_settings:
            bootstrap.servers: "bigdata-kafka-01.chj.cloud:6667,bigdata-kafka-02.chj.cloud:6667,bigdata-kafka-03.chj.cloud:6667,bigdata-kafka-05.chj.cloud:6667,bigdata-kafka-06.chj.cloud:6667"
            fetch.min.bytes: "10240"
            group.id: es-iot-access-consumer 
filters:
    - Grok:
        src: message
        match:
            - '(?ms)^\[(?P<logtime>(.*?))](.*)(?P<msg>(.|\r|\n)*)'
        remove_fields: ["msg"]
    - Date:
        location: 'Asia/Shanghai'
        src: logtime
        formats:
            - '2006-01-02 15:04:05.000'
            - 'RFC3339'
        remove_fields: ["logtime"]
    - Replace:
        fields:
          message: ['^^A',' ']
outputs:
    - Elasticsearch:
        hosts:
            - 'http://superuser:CHEhejia123@172.21.41.21:8200'
        index: 'logstash-%{type}-%{fields.ip_address}-%{+2006-01-02}'
        index_type: "_doc"
        index_time_location: 'Local'
        bulk_actions: 10000
        bulk_size: 80
        concurrent_requests: 5
        flush_interval: 30
        sniff: true
```

**Comment by childe** [comment]
输入的数据给例子

**Comment by niuliwei1029** [comment]
`{"@timestamp":"2020-12-03T17:43:29.093927+08:00","@version":"chj-rsyslog-v8","fields.ip_address":"10.21.35.106","fields.runtime_env":"prod","type":"java_access-dip-analysis-parsecan-autopilot","fields.appname":"dip-analysis-parsecan-autopilot","message":"2020-12-03T09:43:28.946+0000: 636618.471: [GC (Allocation Failure) 2020-12-03T09:43:28.946+0000: 636618.471: [ParNew
Desired survivor size 10485760 bytes, new threshold 1 (max 6)
- age   1:   11181952 bytes,   11181952 total
- age   2:    9789128 bytes,   20971080 total
: 174219K->20480K(184320K), 0.0590041 secs] 2284386K->2134103K(5222400K), 0.0591601 secs] [Times: user=0.13 sys=0.00, real=0.05 secs] ","host":"dip-analysis-parsecan-autopilot-ff794bbfb-b6pc2","source":"/data/logs/prod/dip-analysis-parsecan-autopilot/172.21.120.7/dip-analysis-parsecan-autopilot-ff794bbfb-b6pc2/10.21.35.106/dip-analysis-parsecan-autopilot/gc.log"}`

**Comment by childe** [comment]
Grok 的 Format 写的不对.

大哥, 学习一下 Markdown 语法

**Comment by niuliwei1029** [comment]
好的。Format也能解析出来，只是少量数据解析错误。麻烦指点一下哪里错了？

**Comment by childe** [comment]
1. 时间两边没有中括号。
2. 后面得msg没看懂你要怎么解析



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: niuliwei1029 <notifications@github.com&gt;
发送时间: 2020年12月3日 18:04
收件人: childe/gohangout <gohangout@noreply.github.com&gt;
抄送: childe <rmself@qq.com&gt;, State change <state_change@noreply.github.com&gt;
主题: 回复：[childe/gohangout] 生成null-null的索引，请教下会是哪里的问题 (#116)





 
好的。Format也能解析出来，只是少量数据解析错误。麻烦指点一下哪里错了？

**Comment by niuliwei1029** [comment]
```
{"@timestamp":"2020-12-03T16:19:32.827635+08:00","@version":"chj-rsyslog-v8","fields.ip_address":"10.21.46.68","fields.runtime_env":"prod","type":"java_access-iot-device-shadow","fields.appname":"iot-device-shadow","message":"[2020-12-03 16:15:45.169] [TID: N/A] [XNIO-2 task-158] INFO  com.chehejia.iot.device.shadow.filter.HttpLogFilter =========================================== End ===========================================
","host":"iot-device-shadow-canary-79fb65df9f-mwtdm","source":"/data/logs/prod/iot-device-shadow/172.21.120.145/iot-device-shadow-canary-79fb65df9f-mwtdm/10.21.46.68/iot-device-shadow/iot-device-shadow.log"}
```
这样的也解析出错了。

**Comment by childe** [comment]
右边中括号转义





发自我的iPhone


------------------ 原始邮件 ------------------
发件人: niuliwei1029 <notifications@github.com&gt;
发送时间: 2020年12月3日 18:10
收件人: childe/gohangout <gohangout@noreply.github.com&gt;
抄送: childe <rmself@qq.com&gt;, State change <state_change@noreply.github.com&gt;
主题: 回复：[childe/gohangout] 生成null-null的索引，请教下会是哪里的问题 (#116)





 {"@timestamp":"2020-12-03T16:19:32.827635+08:00","@version":"chj-rsyslog-v8","fields.ip_address":"10.21.46.68","fields.runtime_env":"prod","type":"java_access-iot-device-shadow","fields.appname":"iot-device-shadow","message":"[2020-12-03 16:15:45.169] [TID: N/A] [XNIO-2 task-158] INFO  com.chehejia.iot.device.shadow.filter.HttpLogFilter =========================================== End =========================================== ","host":"iot-device-shadow-canary-79fb65df9f-mwtdm","source":"/data/logs/prod/iot-device-shadow/172.21.120.145/iot-device-shadow-canary-79fb65df9f-mwtdm/10.21.46.68/iot-device-shadow/iot-device-shadow.log"}  
这样的也解析出错了。

**Comment by childe** [comment]
@niuliwei1029 对不起, 我的错, 右边的中括号不用转义.

因为你写了 `remove_fields: ["msg"]` , 所以`msg`字段删掉了
但正则本身也不对, 我不知道你到底想怎么匹配,  应该像类似这样  '(?ms)^\[(?P<logtime>(.*?))](?P<msg>.*)'

**Comment by niuliwei1029** [comment]
原始数据[2020-12-03 16:15:45.169]^^A[TID: N/A]......或者[2020-12-03 16:15:45.169] [TID: N/A]......，我就是想匹配日志时间做替换@timestamp用。但我感觉就算正则匹配不对，也只是匹配message。%{type}-%{fields.ip_address}应该有值才对啊。

**Comment by childe** [comment]
没有 type 和 fields.ip_address 字段吧. 另外这里不支持 fields.ip_address 这种语法.  使用Add放到顶层吧.

**Comment by niuliwei1029** [comment]
```
{"@timestamp":"2020-12-03T16:19:32.827635+08:00","@version":"rsyslog-v8","fields.ip_address":"10.21.46.68","fields.runtime_env":"prod","type":"java_access-iot-device-shadow","fields.appname":"iot-device-shadow","message":"[2020-12-03 16:15:45.169] [TID: N/A] [XNIO-2 task-158] INFO  com.xpeng.iot.device.shadow.filter.HttpLogFilter =========================================== End ===========================================
","host":"iot-device-shadow-canary-79fb65df9f-mwtdm","source":"/data/logs/prod/iot-device-shadow/172.21.120.145/iot-device-shadow-canary-79fb65df9f-mwtdm/10.21.46.68/iot-device-shadow/iot-device-shadow.log"}
```
type 和 fields.ip_address就是内容里面的变量。使用Add放到顶层是什么意思？

**Comment by childe** [comment]
我在手机邮箱里面看的, 没看全前面的消息.  你这样配置应该是可以的.   一个正常的索引都没出来? 全部都是 null 吗? 我觉得应该是有正常的索引的.  null 的索引可能是脏数据造成的.

**Comment by niuliwei1029** [comment]
大部分是正常的。什么情况会出现脏数据啊？有些重要的日志跑到null索引了就搜不到了。用java版的hangout倒没发现这个问题。

**Comment by niuliwei1029** [comment]
消费数据的时候，会生成包含null字符串的索引。从kibana看数据也没解析出来。kibana结果和配置如下：

```
inputs:
    - Kafka:
        topic:
            iot-access: 1 
        codec: json 
        consumer_settings:
            bootstrap.servers: "bigdata-kafka-01.xpeng.cloud:6667,bigdata-kafka-02.xpeng.cloud:6667,bigdata-kafka-03.xpeng.cloud:6667,bigdata-kafka-05.xpeng.cloud:6667"
            fetch.min.bytes: "10240"
            group.id: es-iot-access-consumer 
outputs:
    - Elasticsearch:
        hosts:
            - 'http://user:123456@192.21.41.21:8200'
        index: 'logstash-%{type}-%{fields.ip_address}-%{+2006-01-02}'
        index_type: "_doc"
        index_time_location: 'Local'
        bulk_actions: 10000
        bulk_size: 80
        concurrent_requests: 5
        flush_interval: 30
        sniff: true
```
我把中间的filter去掉，还是会出现logstash-null-null-2020-12-17的索引。还请大神出手解决下
