### ISSUE TITLE
生成数组 list generating

### ISSUE THREAD

**Issue by childe** [childe/gohangout#120]
```
inputs:
    - Stdin:
        codec: json
filters:
    - Add:
        fields:
            tmp: ' ["%{a}", "%{b}"] '  ## extra space before and after
    - Json:
        field: tmp
        target: version
        remove_fields: ['tmp']
outputs:
    - Stdout: {}
```

注意 `' ["%{a}", "%{b}"] '` 这里前后加个空格

另外, 需要做Json解析, 性能会有一些下降.
