### ISSUE TITLE
SetBelongTo级联Filter会导致消息丢失

### ISSUE THREAD

**Issue by WideLee** [childe/gohangout#125]
比如split这个case，https://github.com/childe/gohangout-plugin-examples/tree/master/gohangout-filter-split

如果配置文件是

```
inputs:
    - Stdin: {}

filters:
    - 'split.so':
        sep: ' '
        field: 'message'
    - Add:
	fields:
          "hello": "world"
outputs:
    - Stdout: {}
```

输入`a b c d`不会有Stdout输出
