### ISSUE TITLE
UDP/TCP 添加 client IP 地址

### ISSUE THREAD

**Issue by childe** [childe/gohangout#127]

**Comment by Yullin** [comment]
Nice! 期待这个

**Comment by Yullin** [comment]
可以用add field方式来加吗？

**Comment by childe** [comment]
UDP 的已经添加了。
配置如下：

```
inputs:
    - UDP:
        address: 127.0.0.1:10000
        add_remote_addr: remote

outputs:
    - Stdout: {}
```
