### ISSUE TITLE
加入当前时间

### ISSUE THREAD

**Issue by childe** [childe/gohangout#147]
默认为加入一个 `@timestamp` 字段，就是当前时间。 但如果源数据中已经有这个字段了，我们可能还想加一个当前处理时间的话，如下：

```
inputs:
    - Stdin: {}

filters:
    - Add:
        fields:
            now: '{{now}}'
    - Date:
        src: now
        target: now
        formats:
            - 'UNIX_MS'
outputs:
    - Stdout: {}

```
