### ISSUE TITLE
‘Y’ ‘N’ 转换bool 

### ISSUE THREAD

**Issue by hoysoft** [childe/gohangout#170]
字符 ‘Y’ ‘N’ 如何转换bool

**Comment by childe** [comment]
看了一下代码，目前还有点麻烦。像下面这样是可以的。

```
inputs:
  - Stdin:
      codec: json

filters:
  - Add:
      if:
        - 'EQ($.message,"Y")'
      fields:
        message: 'true'
  - Convert:
      fields:
        message:
          to: bool

outputs:
  - Stdout: {}
```
