### ISSUE TITLE
配置decorate_events: true后，按topic过滤不成功(gohangout-input-confluent-kafka-go)

### ISSUE THREAD

**Issue by bj1116** [childe/gohangout#175]
https://github.com/arterhuo/gohangout-input-confluent-kafka-go
配置如下：
inputs:
  - Ckafka:
      decorate_events: true
      topic:
        topic1: 1
…………………………………………………………
outputs:
  - Stdout:
      if:
         - 'EQ(@metadata,kafka,topic,"topic1")'

没有数据输出，去掉if正常，其他kafka input正常。

**Comment by childe** [comment]
这个Input看起来并没有 decorate_events 参数。

**Comment by bj1116** [comment]
代码里有该参数的，并且不加if条件也能输出meta的相关值；
![image](https://user-images.githubusercontent.com/15172224/166637568-122c0e72-d18a-48fb-bf5a-95b91bbaa3d5.png)

**Comment by childe** [comment]
测下来功能正常，如下。 你把 `不加if条件也能输出meta的相关值` 这个数据发出来看一下。
```yaml
inputs:
  - Stdin:
      codec: json

outputs:
  - Stdout:
      if:
        - 'EQ(@metadata,kafka,topic,"abcd")'
```

```
# cat i |  gohangout --config a.yml -exit-when-nil
gohangout version
{"@metadata":{"kafka":{"topic":"abcd"}},"@timestamp":"2022-05-04T22:45:32.050106+08:00"}

# cat i
{"@metadata":{"kafka":{"topic":"abcd"}}}
{"@metadata":{"kafka":{"topic":"abc"}}}
```
