### ISSUE TITLE
gohangout 内存占用异常

### ISSUE THREAD

**Issue by zcola** [childe/gohangout#176]
版本 1.7.8

有时候会去到 7G 10G，docker stats 后面会降下来，这样内存会很不好限制，如果时从kafka 取了过多数据，能不能反压呢，不然通过cgroup 限制内存容器忙时会挂掉后起不来，不限制又影响宿主资源分配，pprof 默认没开，dump 了一个3g 使用内存的出来

input 这里有另外两个topic ，dump 后我删掉了，这两个本身topic 已经没有任何数据了
```
inputs:
    - Kafka:
        topic:
            saimaan_g18_logtail: 1
        codec: 'json'
        consumer_settings:
            bootstrap.servers: "saimaan.brokers.canal.netease.com:9092"
            group.id: 'logstash_g18_logtail'
            #auto.commit: 'false'
filters:
    - Convert:
        fields:
            batch_offset:
                to: int
            batch_ts:
                to: int
outputs:
    - Elasticsearch:
        sniff:
            refresh_interval: 60
            match: 'EQ($.attributes.zone,"hot")'
        hosts:
            - 'http://7.32.146.90:9200'
            - 'http://7.32.146.117:9200'
        index: 'g18_logtail_write'
        index_type: '_doc'
        concurrent: 4
        bulk_actions: 36000
        bulk_size: 30
        flush_interval: 60
```
