### ISSUE TITLE
gohangout 处理嵌套数据不成功

### ISSUE THREAD

**Issue by KevinLiangX** [childe/gohangout#216]
消息类型：
"kubernetes": {
        "namespace": "default",
        "statefulset": {
            "name": "clickhouse-shard0"
        },
        "labels": {
            "helm_sh/chart": "clickhouse-3.2.1",
            "statefulset_kubernetes_io/pod-name": "clickhouse-shard0-1",
            "app_kubernetes_io/component": "clickhouse",
            "app_kubernetes_io/instance": "clickhouse",
            "app_kubernetes_io/managed-by": "Helm",
            "app_kubernetes_io/name": "clickhouse",
            "controller-revision-hash": "clickhouse-shard0-5cb5bf8df5"
        },
        "container": {
            "name": "clickhouse",
            "image": "docker.io/bitnami/clickhouse:23.3.2-debian-11-r0"
        },
        "node": {
            "name": "host01"
        },
        "pod": {
            "name": "clickhouse-shard0-1",
            "uid": "0c1743a6-4c67-4ed3-90aa-2c74545edb93"
        }
    }

```
inputs:
    - Kafka:
        topic:
            filebeat: 1
        codec: json
        consumer_settings:
            bootstrap.servers: "10.96.3.252:9092"
            group.id: gohangout.filebeat
filters:
    - Add:
        overwrite: true
        fields:
            pod_name: "%{[kubernetes][pod][name]}"
            namespace: '$.kubernetes.namespace'
            container_name: '$.kubernetes.container.name'
            node_name: '$.kubernetes.node'
outputs:
    - Clickhouse:
        table: 'logs.log_queue_all'
        conn_max_life_time: 1800
        username: admin
        password: Fh123456
        hosts:
        - 'tcp://10.96.0.120:9000'
        fields: ['pod_name','namespace','container_name','node_name','message']
        auto_convert: false
        bulk_actions: 1000
        flush_interval: 30
        concurrent: 1
```
clickhouse 表中有 pod_name, namespace ,container_name,node_name等列

使用了jsonPath方式调用数据，和%访问，通过添加一个新的fields 去匹配数据库的列名称，没有生效，这种嵌套的数据该如何处理？
