### ISSUE TITLE
sasl authenticate error : EOF

### ISSUE THREAD

**Issue by auto-sre** [childe/gohangout#221]
按以下配置测试一下并给出结果
kafka 3.4
gohangout 1.9.14

```
inputs:
        - Kafka:
            topic:
                ingress-logs: 1
            codec: json
            consumer_settings:
                bootstrap.servers: "kafka:9092"
                group.id: 'ingress-log'
                max.partition.fetch.bytes: '10485760'
                from.beginning: 'true'
                auto.commit.interval.ms: '5000'
                messages_queue_length: '10'
                sasl.mechanism: 'PLAIN'
                enable.ssl.certificate.verification: false
                security.protocol: SASL_SSL
                ssl.ca.location: /opt/ca.cert
                sasl.user: 'kafkauser'
                sasl.password: ***
- Stdin: {}
filters:
- XXX
outputs:
- Stdout: {}
```

- 输出报错信息
```
E0620 19:42:09.201265       1 broker.go:58] sasl authenticate error : EOF
I0620 19:42:09.201295       1 brokers.go:35] init broker from kafka:9092 error:EOF
F0620 19:42:09.201307       1 kafka_input.go:105] could not init GroupConsumer: could not get any available broker from kafka:9092
```
- 请问是我上面参数写错了还是目前不支持呢
