### ISSUE TITLE
kafka to clickhouse, not format

### ISSUE THREAD

**Issue by solaim** [childe/gohangout#24]
使用kafka console producer生产数据`{date:2012-12-12,level:level,message:test}`,clickhouse建表`create table metrics (date Date,level String,message String) Engine=MergeTree(date,(date,level),8192)`

gohangout仅配置了input和output,kafka的数据能够正常消费，但是写入clickhouse时数据整体写入了message，没有按照字段对应写入，这个应该怎么配置？

**Comment by childe** [comment]
```
Clickhouse:
    table: 'hotel.weblog'
    hosts:
    - 'tcp://10.100.0.101:9000'
    - 'tcp://10.100.0.102:9000'
    fields: ['date', 'level', 'message']
    bulk_actions: 1000
    flush_interval: 30
    concurrent: 1
```
ClickHouse 里面要配置好 fields .

方便的话把你的配置发出来看一下吧.

**Comment by solaim** [comment]
inputs:
    - Kafka:
        topic:
            metrics: 1
        codec: json
        consumer_settings:
            bootstrap.servers: "localhost:9092"
            group.id: test
outputs:
       - Clickhouse:
             table: 'metrics'
             hosts:
                  - 'tcp://localhost:9000'
             fields: ['date','level','message']
             bulk_actions: 10



这是我的配置

**Comment by childe** [comment]
我看着没问题. 你说的 "写入clickhouse时数据整体写入了message，没有按照字段对应写入，这个应该怎么配置",  是指什么? 具体说一下?

**Comment by solaim** [comment]
就是kafka中整体的数据是`{date:2012-12-12,level:level,message:test}`，我的要求是写入clickhouse后，kafka date对应数据表中的date，其余以此类推，但是kafka中的数据整体写入了数据表的message字段

**Comment by childe** [comment]
有些不能确认你的kafka中的数据是不是json格式的.  像下面这样输出看一下呢, 确认一下到底是什么样子的.

```
inputs:
    - Kafka:
        topic:
            metrics: 1
        codec: json
        consumer_settings:
            bootstrap.servers: "localhost:9092"
            group.id: test
outputs:
       - Stdout: {}
```
