### ISSUE TITLE
--reload 当input 为tcp 会提示端口被占用。

### ISSUE THREAD

**Issue by zcola** [childe/gohangout#253]
其实我目的就是传入不同filter 配置进行输出调试（只是filter 变了，input 和 outputs 没变）, gohangout 采用最新版本 1.10

![图片](https://github.com/user-attachments/assets/72a09f84-3aca-48f6-adce-df9371d1ccba)
```
###
inputs:
    #- Stdin: {}
    - TCP:
       network: tcp4
       address: 0.0.0.0:10001
       codec: plain
filters:
  - Json:
      field: msg
outputs:
  - '/opt/gohangout/file_output.so':
      path: '/data/result/uuid.log'

```
