### ISSUE TITLE
kafka to clickhouse int 值过大 变成科学计数

### ISSUE THREAD

**Issue by inertance** [childe/gohangout#257]
E0523 21:22:19.610138    9671 clickhouse_output.go:352] exec clickhouse insert map[@timestamp:2022-05-23 21:22:17.378055136 +0800 CST m=+18101092.586399990 **after:5.119601016832e+15** app_id:1001 before:0 channel_id:101 dataid:15 value:5.119601016832e+15] error: after (Int64): unexpected type string

配置如下:
```yaml
inputs:
    - Kafka:
        topic: 
            prop: 1
        codec: json
        consumer_settings:
            bootstrap.servers: "*************************"
            group.id: prop_to_clickhouse
filters:
  - Convert:
      fields:
        app_id:
            remove_if_fail: false
            to: int
        after:
            remove_if_fail: false
            to: int
        before:
            remove_if_fail: false
            to: int    
        value:
            remove_if_fail: false
            to: int    
outputs:
  - Clickhouse:
      table: 'log.shard_prop'
      hosts:
      - 'tcp://******:9000'
      - 'tcp://******:9000'
      fields: ['app_id','after','before','channel_id','dataid','value','clienttype','from_server_id']
      bulk_actions: 3000
      flush_interval: 3
      concurrent: 1
      username: appuser
      password: *****
  - Stdout:
      if:
        - '{{if .error}}y{{end}}' 
```

**Comment by childe** [comment]
我这边尝试复现一下看。

另外问下看，你的 Gohangout 是使用的哪个版本？

**Comment by inertance** [comment]
没看到哪里有写version的 readme也没有 但是我看了应该是21年之前的



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年10月31日(星期四) 下午5:29
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [childe/gohangout] kafka to clickhouse int 值过大 变成科学计数 (Issue #257)














 
我这边尝试复现一下看。
 
另外问下看，你的 Gohangout 是使用的哪个版本？

**Comment by childe** [comment]
我测试下来，应该是这样的，原始的数据是 `5.119601016832e+15`这样的表达式，直接转Int会失败，应该先转Float，再转Int。像下面这样：

```yaml
filters:
  - Convert:
      fields:
        a:
            remove_if_fail: false
            to: float
  - Convert:
      fields:
        a:
            remove_if_fail: false
            to: int
```
