### ISSUE TITLE
关于把字段值提取到根一层

### ISSUE THREAD

**Issue by yasincyx** [childe/gohangout#259]
配置如下：

```yaml
inputs:
  - Stdin:
      codec: json
outputs:
  - Stdout: {}
```

输入源数据为

>  {"@timestamp":"2024-11-18T17:10:45.252+08:00","base_category":"默认分类","base_category_id":"4dd3183","batch_ts":0,"category_id":"f9a78","data":{"body":"2024-11-18 17:10:43,215 INFO  org.apache.flink.runtime.checkpoint.CheckpointCoordinator","fields":{"AUTH_DEPT":"sa","AUTH_PROJECT":"gd","FLINK_POD_ID":"2523f97b-9f7","FLINK_POD_IP":"100.44.85.44","LAMBDA_METRICS_TAG_LAMBDA_ID":"672daf9ee2","containername":"flink-main-container","logconfig":"workload","namespace":"gdc-sa","nodename":"cn-hangzhou","podip":"100.44.85.44","podname":"dev-ack-log-test-sa235121dk","poduid":"2523f97b-f58f-452b-a036-eedd8ce559f7"}}}

输出如下
![image](https://github.com/user-attachments/assets/1d298c7f-5356-48f7-ab5d-69134f4c61a4)

我该如何把data.fields的内容赋值到根层？

Add到新字段进行json解析和直接对data 和 data.fields json解析都试过了，无法达到预期

**Comment by childe** [comment]
```yaml
inputs:
  - Stdin:
      codec: json
filters:
  - Add:
      fields:
        AUTH_DEPT: '$.data.fields.AUTH_DEPT'
        AUTH_PROJECT: '$.data.fields.AUTH_PROJECT'
outputs:
  - Stdout: {}
```
