### ISSUE TITLE
output 支持条件过滤吗

### ISSUE THREAD

**Issue by iamnotgay** [childe/gohangout#26]
根据条件选择不同的 输出

**Comment by childe** [comment]
可以, 像下面这样

```
- Kafka:
    if:
        -  '(EQ(kubernetes,namespace,"kibana")'
    topic: kibana
    bootstrap.servers: 10.10.0.1:9092
- Elasticsearch:
    ...
```
