### ISSUE TITLE
不同标识数据写入不同clickhouse

### ISSUE THREAD

**Issue by Garry24** [childe/gohangout#260]
有if语句，有else用法吗？ 想实现name="aaa"写入aaa_table表，其他情况下默认写入公共表

```
inputs:
- Stdin: {}
filters:
- XXX
outputs:
  - Clickhouse:
      if:
      - '{{if eq .name "aaa"}}y{{end}}'
      table: aaa_table
      if: 
      - '{{if eq .name "bbb"}}y{{end}}'
      table: bbb_table
```

这样配置岂不是要穷举
