### ISSUE TITLE
规则转换

### ISSUE THREAD

**Issue by abcdbdocker** [childe/gohangout#262]
logstash规则:
```
filter:
 if [foo] == "bar" and [severity] == "INFO"{
      drop{ }
    }
    if [hello] == "world" and [severity] == "INFO" {
   	  drop{ }
    }
```
这个这个形式的如何用gohangout转换呢？让gohangout可以适配这个规则 我查了gohangout示例只有单个规则啊 Drop:
    if:
      - '{{if .name}}y{{end}}'
      - '{{if eq .name "childe"}}y{{end}}'
      - '{{if or (before . "-24h") (after . "24h")}}y{{end}}'

**Comment by childe** [comment]
```yaml
inputs:
  - Stdin:
      codec: json

filters:
  - Drop:
      if:
        - 'EQ($.foo,"bar") && EQ($.severity,"INFO")'
  - Drop:
      if:
        - 'EQ($.hello,"world") && EQ($.severity,"INFO")'

outputs:
  - Stdout:
      codec: json
```
