### ISSUE TITLE
Rename Filter 不支持嵌套字段

### ISSUE THREAD

**Issue by jingleniko** [childe/gohangout#268]
按以下配置测试一下并给出结果

- 源数据
```
{"data": {"timestamp": "11"}}
```

- 配置文件
```
inputs:
- Stdin: {}
filters:
- Json:
    field: message
    remove_fields:
    - message
    failTag: _extractfailure
- Rename:
    fields:
      '[data][timestamp]': '[data][ts]'
outputs:
- Stdout: {}
```

- 输出
```
{"@timestamp":"2025-02-13T15:24:20.392877+08:00","data":{"timestamp":"11"}}
```
- 期望
```
{"@timestamp":"2025-02-13T15:24:20.392877+08:00","data":{"ts":"11"}}
```

----------

自己尝试开发 `filter/rename.go` 支持嵌套字段形式，最终止步于 vr.Render(event) 时，无法得到原字段是否已存在于 event 中，即，无法区分

1\ 原字段存在, 值为 nil
2\ 原字段不存在

这两种情况，也就是当发生上述情况时，无法正确地对应地去处理。如果改动 vr.Render 的话，变更会太多，所以还是交给大佬了。

----------

贴下我尝试更改的代码：
```go
package filter

import (
	"github.com/childe/gohangout/topology"
    "github.com/childe/gohangout/field_setter"
	"github.com/childe/gohangout/value_render"
    "github.com/childe/gohangout/field_deleter"

	"k8s.io/klog/v2"
)

type RenameFilter struct {
	config map[interface{}]interface{}
	fields map[string]field_setter.FieldSetter
}

func init() {
	Register("Rename", newRenameFilter)
}
func newRenameFilter(config map[interface{}]interface{}) topology.Filter {
	plugin := &RenameFilter{
		config: config,
		fields: make(map[string]field_setter.FieldSetter),
	}

	if fieldsValue, ok := config["fields"]; ok {
		for k, v := range fieldsValue.(map[interface{}]interface{}) {
			vfs := field_setter.NewFieldSetter(v.(string))
			plugin.fields[k.(string)] = vfs
		}
	} else {
		klog.Fatal("fileds must be set in rename filter plugin")
	}
	return plugin
}

func (plugin *RenameFilter) Filter(event map[string]interface{}) (map[string]interface{}, bool) {
	for sourceF, targetFs := range plugin.fields {
	    vr := value_render.GetValueRender2(sourceF)
	    v := vr.Render(event)
            targetFs.SetField(event, v, "", true)
            sourceFd := field_deleter.NewFieldDeleter(sourceF)
            sourceFd.Delete(event)
	}
	return event, true
}

```
