### ISSUE TITLE
output导入clickhouse,显示 字段名 (Int64): unexpected type string

### ISSUE THREAD

**Issue by caohuigh** [childe/gohangout#27]
报错日志:
error: server (Int64): unexpected type string
启动日志:
row desc: output.rowDesc{Name:"server", Type:"Int64", DefaultType:"", DefaultExpression:""}
我在config.yml文件里配置:
fields: [server, 'ip', id]
请教一下,是不是clickhouse里的表字段是int64,yml文件里fields里面对应字段就不加单引号?
加单引号的即表示clickhouse里面对应字段是string类型?
我试了一下,将fields里面的字段全部加上'  ',会显示:
row desc: output.rowDesc{Name:"字段名", Type:"String"......省略....

当fields里面的字段全部加上单引号时需要把clickhouse里面的表对应字段全部改成string才能写入成功,且只有这种方式可以写入成功.
但只要表中包含int64类型的字段,就会报出错误日志 error: 字段名 (Int64): unexpected type string.
对go不是很懂,您是在源码里将从kafka里接收的数据全部改成string类型然后开始写入clickhouse的吗?
我的源数据:
{"server":666,"ip":"1.2.3.4","id":100}
server和id字段应该是int64类型,ip是string类型,但只有fields和clickhouse表里全设置成string类型才能写入,否则就报error.不明白是什么原因.

**Comment by caohuigh** [comment]
@childe  谢谢回复，您指的是使用FILTER里面的convert？我主要是想把string类型转成int64，格式是怎样的，可以给个例子吗？

**Comment by childe** [comment]
```
Convert:
    fields:
        server:
            setto_if_fail: 0
            to: int
        ip:
            to: int
            setto_if_fail: 0
```

**Comment by caohuigh** [comment]
> 
> 
> ```
> Convert:
>     fields:
>         server:
>             setto_if_fail: 0
>             to: int
>         ip:
>             to: int
>             setto_if_fail: 0
> ```

不好意思,是我没说清楚引起误解了,我想请教的是Convert应该放在什么位置?是放在filters下面吗?
比如这样:
inputs:
    - Kafka:
        topic:
          ... ...
filters:
    - Convert:
      fields:
          server:
              to: int
              remove_if_fail: false
          id:
              to: int
              remove_if_fail: false
outputs:
    - Clickhouse:
          ... ...

但是我这样写运行的时候却报错了:
I0509 15:52:21.857921  187339 filter.go:72] filter type: Convert
panic: interface conversion: interface {} is nil, not map[interface {}]interface {}

goroutine 27 [running]:
github.com/childe/gohangout/filter.BuildFilterBoxes(0xc0001b5a40, 0x9f6740, 0xc0001e9630, 0x1, 0x0, 0x0)

我在output中的fields中是这样写的:
fields: ['server', 'ip', 'id']
我也试过:
fields: [server, 'ip', id]
但无论使用fields的哪种写法,结合上面的Convert时都会报错,是我哪里格式写错了吗?

**Comment by zhoufwind** [comment]
@caohuigh 我这边试了下，好像没遇到你说的报错，这个配置你试下？
indexer-kafka-test.yml
```yaml
inputs:
    - Stdin:
        codec: json

filters:
    - Convert:
        fields:
            server:
                setto_if_fail: 0
                to: int
            id:
                setto_if_fail: 0
                to: int

outputs:
    - Stdout: {}
```

```bash
gohangout --config indexer-kafka-test.yml
{"server":666,"ip":"1.2.3.4","id":100}
{"server":666,"ip":"1.2.3.4","id":100,"@timestamp":"2019-05-09T18:21:38.904303797+08:00"}
```
