### ISSUE TITLE
if语法失效

### ISSUE THREAD

**Issue by PKFresher** [childe/gohangout#36]
在使用if 的语法中,发现一直不起作用
```
filters:
    - Filters:
       if:
           - '{{if eq [var_field][event_name] "enter_item"}}y{{end}}'
       filters:
           - Add:
              fields:
                name: childe
```
-------------------------------------------------------------------第二种写法-------
```
filters:
    - Filters:
       if:
           - 'EQ(var_field,event_name "enter_item")'
       filters:
           - Add:
              fields:
                name: childe
```

在使用最近的relese中依然无效

**Comment by childe** [comment]
```
filters:
    - Add:
    if:
    - 'EQ(var_field,event_name "enter_item")'
    fields:
      name: childe
```
你先试一下这样呢? 我看看是不是 Filters 有问题
