### ISSUE TITLE
动态调整随机采样率

### ISSUE THREAD

**Issue by childe** [childe/gohangout#46]

**Comment by childe** [comment]
在Translate中, 根据当前时间生成一个随机数, 然后通过字典文件映射到一个另外一个字段.  字典文件可以定时刷新.

Translate 配置
```
filters:
    - Translate:
        dictionary_path: http://127.0.0.1:8080/d.yml
        refresh_interval: 100000
        source: '{{mod now 10}}'
        target: a
    - Drop:
        if:
        - 'EQ(a,0)'
```

字典文件配置
```
"0": 1
"1": 1
"2": 1
"3": 1
"4": 1
"5": 1
"6": 1
"7": 1
"8": 0
"9": 0
```
