### ISSUE TITLE
ClickHouse写入遇到的2个问题

### ISSUE THREAD

**Issue by wkshare** [childe/gohangout#48]
**问题1: ClickHouse写入数据都空，数据条目在不断新增，但是插入的数据条目都是空记录。**
如题的现象，没有任何报错日志，打开-v 5，也没有任何的错误信息。

**问题1: JSON格式的数据，包含子对象，如何转换成field插入到clickhouse**
例如json数据为：
{
  "a": "aa",
  "bb": { 
    "x": "xx",
    "y": "yy"
  },
  "c": "cc"
}
如上数据，x和y，如何插入到clickhouse的x和y字段呢？

**Comment by wkshare** [comment]
再补充请教第三个问题：
我的数据时间格式是UTC的，如何转成unix timestamp存入clickhouse。
filter的功能能给个示例吗？

**Comment by wkshare** [comment]
问题1，问题2，我解决了。

问题3，继续请求赐教：）

**Comment by chijiajian** [comment]
@wkshare  嵌套json的实例可以给一个吗？ 我在配置这个的时候也没有成功。就是你的问题2是怎么解决的？thx

**Comment by wkshare** [comment]
@chijiajian 

fields:
    x: '[bb][x]'

**Comment by childe** [comment]
@wkshare 抱歉最近工作太忙了, 才刚刚看到 :(

```
Date:
  src: timestamp
  target: timestamp
  location: 'Etc/UTC'
  format:
    - 20060102XXXXX // 按你实际的来
```

大概这样吧, 你看行吗
