### ISSUE TITLE
如果只取json中的个别字段存入es，怎么写配置文件？

### ISSUE THREAD

**Issue by libojia-aug** [childe/gohangout#52]

**Comment by childe** [comment]
目前还不行, 后面实现一下.

**Comment by childe** [comment]
现在只能这样实现

```
- Json:
   field: msg
   target: temp
- Add:
   fields:
     name: '[temp][name]'
     age: '[temp][age]'
     remove_fields: ['temp']

```
