### ISSUE TITLE
input嵌套JSON问题

### ISSUE THREAD

**Issue by telltime** [childe/gohangout#57]
INPUT是嵌套json
比如

```json
｛
database：test
，data｛
id：12
，name：tt
｝
｝
```
这种我要去id，name，不需要类型转换等其他操作，怎么取出来？

**Comment by childe** [comment]
```yaml
Add:
  fields:
    id: '[data][id]'
    name: '[data][nam]'
```

是这个意思吗?
