### ISSUE TITLE
请问消费kafka多topic，每个topic对应clickhouse一张表，配置文件该怎么写?谢谢！

### ISSUE THREAD

**Issue by gc1024** [childe/gohangout#58]
现在单topic入一张表是这么写的：

```
inputs:
    - Kafka:
        topic:
            test: 1
        codec: json
        consumer_settings:
            bootstrap.servers: "localhost:9092"
            group.id: gohangout.test
            max.partition.fetch.bytes: '100'
            auto.commit.interval.ms: '1000'
filters:
    - Date:
        src: 'edate'
        location: Asia/Shanghai
        formats:
            - '2006-01-02'
        remove_fields: ["@timestamp"]
outputs:
    - Clickhouse:
         table: 'test.table1'
         hosts:
         - 'tcp://192.168.0.119:9000'
         fields: ['edate','record_id','server']
         bulk_actions: 1
         flush_interval: 1
         concurrent: 1
```
