### ISSUE TITLE
kafka连接错误

### ISSUE THREAD

**Issue by saperliu** [childe/gohangout#65]
错误：
get broker[0] error:could not init broker for node[0](localhost:9092):failed to establish connection when init broker: dial tcp [::1]:9092: connectex: No connection could be made because the target machine actively refused it.

配置文件如下:
```
inputs: 

    - Stdin:

        codec: json

    - Kafka:
        topic:
            topic-A: 1
        #assign:
            #test: [0, 9]
        codec: json
        consumer_settings:

            bootstrap.servers: 192.168.1.103:9092

            group.id: hangout.test
```
