### ISSUE TITLE
grok表达式支持放到子字段

### ISSUE THREAD

**Issue by ever4Keny** [childe/gohangout#75]
有名称的捕获里面支持放到子字段，例如：
%{GREEDYDATA:digest.tag1}
要把结果放到digest的子字段tag1，可以做到嘛？
尝试了使用正则的有名称的捕获，也不行：
(?P<digest.preTag>.*)
直接报语法错误了。
这个在logstash是可以支持的。
两种解决方案，要不就直接支持放到子字段，要不grok再加一个属性，指定放到哪个字段下面，默认在最顶层。

**Comment by childe** [comment]
这个需要改一下代码, 在目前的代码下, 需要这样处理了: 

```
    - Grok:
        src: message
        match:
            - '%{GREEDYDATA:tag1}'
        remove_fields: ['message']
    - Add:
         fields:
           digest.tag1: tag1
        remove_fields:
        - tag1
           
```
