### ISSUE TITLE
无法正常output到clickhouse

### ISSUE THREAD

**Issue by icelengbing** [childe/gohangout#76]
--配置文件 config-clickhouse.yml 如下：
```
inputs:
    - Kafka:
        topic:
            test: 1
        codec: json
        consumer_settings:
            bootstrap.servers: "xxx.xxx.xxx.xxx:9092"
            group.id: test-consumer
            max.partition.fetch.bytes: '10485760'
            #from.beginning: 'true'
outputs:
    - Clickhouse:
        table: 'default.test'
        username: 'test'
        password: 'test'
        hosts:
            - 'http://xxx.xxx.xxx:8080'
        fields: ['test1','test2','test3']
        bulk_actions: 10000
```

--运行后报错如下：
```
gohangout.exe -v 5 --config config-clickhouse.yml
E0219 10:13:16.277954   18868 clickhouse_output.go:227] clickhouse ping error: [hello] unexpected packet [72] from server
F0219 10:13:16.282922   18868 clickhouse_output.go:239] no available host
goroutine 27 [running]:
github.com/golang/glog.stacks(0xc00015a900, 0xc0001c6120, 0x4a, 0x101)
```

--当前clickhouse版本和访问情况如下：version 19.16.10.44
--直接访问返回 ok
```
curl "http://xxx.xxx.xxx.xxx:8080"
Ok.
```
--带username和password参数访问返回错误的default用户密码（username参数无效）：
```
curl "http://xxx.xxx.xxx.xxx:8080/?username=test&password=test"          
Code: 193, e.displayText() = DB::Exception: Wrong password for user default (version 19.16.10.44)

```
--带user和password参数访问返回空查询（用户名和密码都有效）：
```
curl "http://xxx.xxx.xxx.xxx:8080/?user=test&password=test"
Code: 62, e.displayText() = DB::Exception: Empty query (version 19.16.10.44)

```
我看源码中逻辑是这样的：
https://github.com/childe/gohangout/blob/master/output/clickhouse_output.go

`dataSourceName := fmt.Sprintf("%s?username=%s&password=%s", host, p.username, p.password)
`
这里是不是有问题，首先dataSourceName拼装时参数不对，是username，而当前clickhouse文档中给出的参数应该是user。其次就算user参数没问题，但是直接访问还是会返回DB异常。这段过不去。
```
			if err := db.Ping(); err != nil {
				if exception, ok := err.(*clickhouse.Exception); ok {
					glog.Errorf("[%d] %s \n%s\n", exception.Code, exception.Message, exception.StackTrace)
				} else {
					glog.Errorf("clickhouse ping error: %s", err)
				}
			} else {
				dbs = append(dbs, db)
			}

```
麻烦请看一下这个问题如何修正，当前我无法将数据output到clickhouse (version 19.16.10.44)

谢谢。
