### ISSUE TITLE
centos7 kafka 0.11.0.0 SASL/PLAIN  认证失败

### ISSUE THREAD

**Issue by shamohong1215** [childe/gohangout#81]
```
inputs:
   - Kafka:
        topic:
            xxxx: 1
        codec: 'json'
        consumer_settings:
            bootstrap.servers: "xxxx"
            group.id: 'gohangout'
            max.partition.fetch.bytes: '10485760'
            auto.commit.interval.ms: '5000'
            sasl.mechanism: 'PLAIN'
            sasl.user: 'xxx'
            sasl.password: 'xxxxx'
            kafka.version: '0.11.0.0'
outputs:
    - Stdout: {}
```

消费kafka数据报错 
request length: 21. api: 17 CorrelationID: 1 timeout: 30000
sasl authenticate error : EOF
