### ISSUE TITLE
Convert阶段to: float ，setto_if_fail设置成0 output 为clickhouse会报错

### ISSUE THREAD

**Issue by xzhongwang** [childe/gohangout#92]
```
- Convert:
        fields:
            geo_lat:
                remove_if_fail: false
                setto_if_fail: 0.0
                to: float  
```
setto_if_fail设置成0报错：error: geo_lat (Float64): unexpected type int
需要设置成0.0才能正常
