### ISSUE TITLE
建议添加split 拆分事件filter 

### ISSUE THREAD

**Issue by TerrellXu** [childe/gohangout#96]
logstash里面split 插件可以把一行数据，拆分成多个事件。
在日志压缩的场景下需要依赖这个插件完成日志拆分操作，建议添加该filter～
下图为拆分事件效果
![image](https://user-images.githubusercontent.com/16453240/87017046-123e0900-c202-11ea-91ef-7aeab8756332.png)

**Comment by childe** [comment]
https://github.com/childe/gohangout-plugin-examples/tree/master/gohangout-filter-split

**Comment by childe** [comment]
t.yml

```
inputs:
    - Stdin: {}

filters:
    - 'split.so':
        field: message
        sep: '#'
        drop_original_event: false
        deep_copy: true

outputs:
    - Stdout: {}
```

运行输出
```
% echo 'abcd#xyz#123'  | build/gohangout --config t.yml
{"@timestamp":"2020-07-09T23:12:09.205893+08:00","message":"abcd"}
{"@timestamp":"2020-07-09T23:12:09.205893+08:00","message":"xyz"}
{"@timestamp":"2020-07-09T23:12:09.205893+08:00","message":"123"}
{"@timestamp":"2020-07-09T23:12:09.205893+08:00","message":"abcd#xyz#123"}
```
